name: Deploy Front

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: "18"

    - name: Install Dependencies and Build
      run: |
        npm ci
        npm run build

    - name: Stop and Prepare Web Directory on EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          echo "âž¡ Criando pasta base /var/www..."
          sudo mkdir -p /var/www

          echo "âž¡ Backup do front antigo..."
          if [ -d /var/www/trackon-web ]; then
            timestamp=$(date +'%Y%m%d%H%M%S')
            sudo cp -r /var/www/trackon-web "/var/www/trackon-web_backup_$timestamp"
            echo "Backup criado: /var/www/trackon-web_backup_$timestamp"
          fi

          echo "âž¡ Limpando diretÃ³rio antigo..."
          sudo rm -rf /var/www/trackon-web
          sudo mkdir -p /var/www/trackon-web
          sudo chown -R ec2-user:ec2-user /var/www/trackon-web
          sudo chmod -R 755 /var/www/trackon-web

    - name: Upload Build to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        source: "build/**"
        target: "/var/www/trackon-web/"
        overwrite: true
        strip_components: 1

    - name: Finalize Deployment
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          echo "âž¡ Ajustando permissÃµes para o Nginx..."
          sudo chown -R nginx:nginx /var/www/trackon-web
          sudo chmod -R 755 /var/www/trackon-web

          echo "âž¡ Recarregando Nginx..."
          sudo systemctl reload nginx

          echo "ðŸŽ‰ Deploy do front concluÃ­do com sucesso!"
