name: Deploy Front

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: "18"

    - name: Install and Build React
      run: |
        npm ci
        npm run build

    - name: Prepare Web Directory
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          timestamp=$(date +'%Y%m%d%H%M%S')

          echo "Criando backup do front atual..."
          sudo mkdir -p /var/www
          if [ -d /var/www/trackon-web ]; then
            sudo cp -r /var/www/trackon-web "/var/www/trackon-web_backup_$timestamp"
          fi

          echo "Limpando diretÃ³rio antigo..."
          sudo rm -rf /var/www/trackon-web
          sudo mkdir -p /var/www/trackon-web
          sudo chown -R ec2-user:ec2-user /var/www/trackon-web

    - name: Upload Build to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        source: "build/*"
        target: "/var/www/trackon-web/"

    - name: Finalize Deployment
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          sudo chown -R nginx:nginx /var/www/trackon-web
          sudo chmod -R 755 /var/www/trackon-web

          echo "ðŸ”„ Recarregando o Nginx..."
          sudo systemctl reload nginx

          echo "Deploy do front concluÃ­do com sucesso!"
